print(start:foo())
print(start:bar(123))
print(start:baz(456,789))
print(start:quux())

print(start:getMsg())
obj = start:gimme()
print(obj:getMsg())
obj:setMsg("foobar")
print(start:getMsg())
print(obj:getMsg())
print(obj:test(start))
